pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', views.SearchResultsView.as_view(), name='search-results'),

    path('tags/', views.TagListView.as_view(), name='tag-list'),
    path('tags/<slug:slug>/', views.TagDetailsView.as_view(),
         name='tag-details'),

    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

    path('public/<int:pk>/', views.PublicProfileView.as_view(), name='public_profile'),
    path('public/<int:pk>/<str:action>/', views.UserActionView.as_view(), name='user-action'),
    path('public/comment/<int:pk>/', views.CommentView.as_view(), name='comment-view'),

    path('favourite_profile/<int:pk>/', views.add_favourite, name="add-favourite"),
    path('favourites/', views.list_favourites, name="list-favourites"),


    path('categories/', views.CategoryListView.as_view(), name='category-list'),
    path('categories/<str:cat>/', views.CategoryDetailsView.as_view(), name='category-details'),
]

rojgar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('signin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

signin/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    available_for_hire = models.BooleanField(default=False)
    occupation = models.CharField(max_length=50, blank=True, default='')
    image = models.ImageField(upload_to="profile_pictures/%Y%m%d", default="", null=True, blank=True)
    cover_image = models.ImageField(upload_to="cover_images/%Y%m%d", default="", null=True, blank=True)

    category_choices = (
        ("P&T","Programming & Technology"),
        ("G&D","Graphics & Design"),
        ("DM","Digital Marketing"),
        ("W&T","Writing & Translation"),
        ("DE","Data Entry"),
        ("V&M","Video & Animation"),
        ("M&A","Music & Audio"),
        ("B&I","Business & Investment"),
        ("CS","Consulting Service"),
        ("M&P","Medical & Pharma"),
        ("AH","Architect Designs"),
        ("LI","Lifestyle"),
        ("AUD","Audit & Taxation"),
        ("QA","Quality Assurance"),
        ("ENG","Engineering Consultancy"),
        ("OM", "Organization Management"),
        ("RP","Repair & Technical Support"),
        ("E&T","Education & Teaching"),
    )

    category = models.CharField(max_length=40, choices=category_choices, default='E&T',)
    description = models.TextField(max_length=1000, default='', blank=True)

    gender_choices = (
        ("M","Male"),
        ("F","Female"),
        ("O","Other"),
    )
    gender = models.CharField(max_length=13, choices=gender_choices, blank=True,
                             default='')
    education = models.CharField(max_length=24, blank=True, default='')
    skills = TaggableManager(verbose_name='skills', blank=True)
    price = models.PositiveIntegerField(default=0, blank=True)
    website = models.URLField(max_length=250, null=True, blank=True)
    joined_at = models.DateTimeField(auto_now_add=True)
    favourite = models.ManyToManyField(User, related_name='favourite', blank=True)


class Hiree(models.Model):
    hirees = models.ManyToManyField(User)
    hirer = models.ForeignKey(User, on_delete=models.CASCADE, null=True,
                                     related_name='hirer')

    @classmethod
    def hire(_class, hirer, new_hiree):
        _hirer, created = _class.objects.get_or_create(hirer=hirer)
        _hirer.hirees.add(new_hiree)

    @classmethod
    def free(_class, hirer, new_hiree):
        _hirer, created = _class.objects.get_or_create(hirer=hirer)
        _hirer.hirees.remove(new_hiree)


class Comment(models.Model):
    user      = models.ForeignKey(User, on_delete=models.CASCADE)
    profile   = models.ForeignKey(Profile, on_delete=models.CASCADE)
    body      = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body

templates/pages/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

	<div class="service" style="padding-bottom: 2em;">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-4">
					<div class="card user-card">
						<div class="card-body" style="height: 17em;">
							<div class="dashboardmain">
								<div class="dashuserimg">
									{% if user.profile.image %}
									<img src={{ user.profile.image.url }} height="100%" width="100%" style="object-fit: cover;object-position: center center;">
									{% else %}
									<img src="{% static 'images/default_profile_pic.png' %}" height="100%" width="100%" />
									{% endif %}
								</div>
							</div>
							<center><a style="margin-bottom: 2em;margin-top: 1em;" href="{% url 'public_profile' user.id %}" class="btn btn-info">View Public Profile</a></center>
						</div>
					</div>
				</div>
				<div class="col-12 col-md-8">
					<div class="card user-card">
						<div class="card-body" style="height: 17em;">
							<p>
								<span style="font-size: 30px;">Welcome {{ user.username }}</span>
								<br/>{{ user.email }}
							</p>
							<p>
								Status:
								{% if user.profile.available_for_hire %}
									<span class="text-info">Active as Rojgar Worker</span>
								{% else %}
									<span class="text-danger">Inactive as Rojgar Worker</span><br/><span class="sml-text">Update your profile to open up yourself to the world!</span>
								{% endif %}
							</p>
							<div class="d-flex justify-content-start justify-content-between mt-5">
								<a href="{% url 'profile' %}" class="btn btn-info btn-sm"><i class="fas fa-pen"></i>  Edit Profile</a>
								<form action="{% url 'logout' %}" method="POST">
									{% csrf_token %}
									<button type="submit" class="btn btn-danger btn-sm">
										Logout <i class="fas fa-sign-out-alt"></i>
									</button>
								</form>
							</div>
						</div>
					</div>
				</div>
				<div class="col-12">
					<div class="card user-card">
						<div class="card-body">
							<h5 class="page-title">Jobs given by you:</h5>
							<table class="table table-hover">
								<tbody style="text-align: center;">
									{% if incomings %}
										{% for item in incomings %}
											<tr>
												<td><a href="{% url 'public_profile' item.id %}">{{ item.username }}</a></td>
												<td>
													<form action="{% url 'user-action' item.id 'free' %}" method="POST">
														{% csrf_token %}
														<button type="submit" class="btn btn-warning text-white"> Free </button>
													</form>
												</td>
											</tr>
										{% endfor %}
									{% else %}
										<td class="text-muted">No current incoming transactions.</td>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="col-12">
					<div class="card user-card">
						<div class="card-body">
							<h5 class="page-title">Jobs given to you:</h5>
							<table class="table table-hover">
								<tbody style="text-align: center;">
									{% if outgoings %}
										{% for item in outgoings %}
											<tr>
												<td><a href="{% url 'public_profile' item.hirer.id %}">{{ item.hirer.username }}</a></td>
											</tr>
										{% endfor %}
									{% else %}
										<td class="text-muted">No current outgoing transactions.</td>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/pages/profile.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container">
	
	<h2 class="mt-5">Profile Page</h2>
	<h5>Fill the data carefully as Employers are going to give job based on these data.</h5>
	
	<form method="post" action="{% url 'profile' %}" enctype="multipart/form-data" name="workprofile" onsubmit="return validate_for_available()" class="mt-5">
		{% csrf_token %}
		<div class="row">
			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_username">Username</label>
				<input type="text" name="username" class="form-control" id="id_username" value="{{user.username}}">
			</div>
			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_first_name">First name</label>
				<input type="text" name="first_name" class="form-control" id="id_first_name" value="{{user.first_name}}">
			</div>
			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_last_name">Last name</label>
				<input type="text" name="last_name" class="form-control" id="id_last_name" value="{{user.last_name}}">
			</div>

			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_occupation">Occupation</label>
				<input type="text" name="occupation" class="form-control" id="id_occupation" value="{{user.profile.occupation}}">
			</div>

			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_category">Category</label>
				<select name="category" id="id_category" class="form-control">
					<option value="P&T" {% if user.profile.category == 'P&T' %}selected{% endif %}> Programming & Technology</option>
					<option value="G&D" {% if user.profile.category == 'G&D' %}selected{% endif %}> Graphics & Design</option>
					<option value="DM" {% if user.profile.category == 'DM' %}selected{% endif %}> Digital Marketing</option>
					<option value="W&T" {% if user.profile.category == 'W&T' %}selected{% endif %}> Writing & Translation</option>
					<option value="DE" {% if user.profile.category == 'DE' %}selected{% endif %}> Data Entry</option>
					<option value="V&M" {% if user.profile.category == 'V&M' %}selected{% endif %}> Video & Animation</option>
					<option value="M&A" {% if user.profile.category == 'M&A' %}selected{% endif %}> Music & Audio</option>
					<option value="B&I" {% if user.profile.category == 'B&I' %}selected{% endif %}> Business & Investment</option>
					<option value="CS" {% if user.profile.category == 'CS' %}selected{% endif %}> Consulting Service</option>
					<option value="AH" {% if user.profile.category == 'AH' %}selected{% endif %}> Architect Designs</option>
					<option value="LI" {% if user.profile.category == 'LI' %}selected{% endif %}> Lifestyle</option>
					<option value="M&P" {% if user.profile.category == 'M&P' %}selected{% endif %}> Medical & Pharma</option>
					<option value="AUD" {% if user.profile.category == 'AUD' %}selected{% endif %}> Audit & Taxation</option>
					<option value="QA" {% if user.profile.category == 'QA' %}selected{% endif %}> Quality Assurance</option>
					<option value="ENG" {% if user.profile.category == 'ENG' %}selected{% endif %}> Engineering Consultancy</option>
					<option value="OM" {% if user.profile.category == 'OM' %}selected{% endif %}> Organization Management</option>
					<option value="RP" {% if user.profile.category == 'RP' %}selected{% endif %}> Repair & Technical Support</option>
					<option value="E&T" {% if user.profile.category == 'E&T' %}selected{% endif %}> Education & Teaching</option>
				</select>
			</div>

			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_gender">Gender</label>
				<select name="gender" class="form-control" id="id_gender">
					<option value="M" {% if user.profile.gender == 'M' %}selected{% endif %}> Male</option>
					<option value="F" {% if user.profile.gender == 'F' %}selected{% endif %}> Female</option>
					<option value="O" {% if user.profile.gender == 'O' %}selected{% endif %}> Others</option>
				</select>
			</div>

			<div class="col-sm-12 col-lg-9 form-group">
				<label for="id_image">Profile Picture</label>
				<input type="file" name="image" placeholder="Profile Picture" value="{{ user.profile.image }}" id="id_image" class="form-control" accept="image/*"/>
			</div>

			<div class="col-sm-12 col-lg-9 form-group">
				<label for="id_cover">Cover Image</label>
				<input type="file" name="cover_image" placeholder="Cover Image" id="id_cover_image" value="{{ user.profile.cover_image }}" class="form-control" accept="image/*"/>
				<small id="usernameHelp" class="form-text text-muted">Upload your cover images or your finished work snap</small>
			</div>

			<div class="col-sm-12 col-lg-4 form-group">
				<label for="id_skills">Tags</label>
				<input type="text" name="skills" class="form-control" id="id_skills"
				value="{% for skill in user.profile.skills.all %}{{ skill }}, {% endfor %}"/>
			</div>

			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_education">Education</label>
				<input type="text" name="education" class="form-control" id="id_education" value="{{user.profile.education}}">
			</div>

			<div class="col-sm-12 col-md-6 col-lg-4 form-group">
				<label for="id_price">price</label>
				<input type="number" name="price" placeholder="enter amount in nepali rupees" class="form-control" id="id_price" value="{{ user.profile.price }}">
			</div>

			<div class="col-12 form-group">
				<label for="id_description">Description</label>
				<textarea name="description" class="form-control" id="id_description">{{user.profile.description}}</textarea>
			</div>
			<div class="col-12 form-group">
				<label for="id_website">Website</label>
				<input type="url" name="website" class="form-control" id="id_website" {% if user.profile.website %}value="{{user.profile.website}}"{% endif %}>
			</div>
			<div class="col-12 form-group">
				<p>Available for hire :
					<input class="p-3 " type="checkbox" name="available_for_hire" class="form-control"
																  id="id_available_for_hire"{% if user.profile.available_for_hire %}checked{% endif %} />
				</p>
			</div>
			<h5 id="e_message" class="col-12"></h5>
			<button type="submit" value="update" class="btn btn-primary">Update</button>
		</div>
	</form>
</div>

{% else %}
<h1 class="text-disabled notfound">Forbidden!</h1>
{% endif %}


{% endblock %}

templates/pages/profile_favourite_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <h2 class="page-title">My Saved Profiles</h2>
  </div>

  {% if favs %}
  <div class="service" style="padding-bottom: 2em;">
    <div class="container">
      <div class="row">
        {% for fav in favs %}
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class="card user-card">
              {% if fav.profile.cover_image %}
              <img class="card-img-top user-card-image" src={{ fav.profile.cover_image.url }} alt="Card image">
              {% else %}
              <img class="card-img-top user-card-image" src="{% static 'images/default_cover_pic.jpg' %}">
              {% endif %}

              <div class="card-body">
                <div class="user-description">
                  <div class="user-header">
                    {% if fav.profile.image %}
                    <img src="{{ fav.profile.image.url }}" style="width: 2em; height: 2em;border-radius: 2em;object-fit: cover;object-position: center center">
                    {% else %}
                    <div style="width: 2em; height: 2em;border-radius: 2em;background-image: url({% static 'images/default_profile_pic.png' %});background-color: grey;background-size: 2em 2em;"></div>
                    {% endif %}
                    <div style="padding-left: 1em;">
                      <b>{{ fav.username }}</b></br>
                      <span class="sml-text">{{ fav.profile.occupation }}</span>
                    </div>
                  </div>

                  <p class="card-text sml-text">{{ fav.profile.description }}</p>
                </div>
                <hr/>
                <div class="clearfix"> 
                  <span class="float-left sml-text">NRs. <b class="text-success" style="font-size: 18px;">{{ fav.profile.price }}</b></span>
                  <a href="{% url 'public_profile' fav.id %}" class="btn btn-info float-right">View Profile</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  {% else %}
    <p class="display-3 text-muted notfound">No Profiles Saved!</p>
  {% endif %}
{% endblock %}

templates/pages/public_profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
	<div class="service pb-4" style="min-height: 100vh;">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-4">
					<div class="card user-card">
						<div class="card-body">
							<div class="dashboardmain">
								<div class="dashuserimg">
									{% if profile.image %}
										<img src={{ profile.image.url }} height="100%" width="100%" style="object-fit: cover;object-position: center center;">
									{% else %}
										<img src="{% static 'images/default_profile_pic.png' %} " height="100%" width="100%">
									{% endif %}
								</div>
							</div>
							<div style="text-align: center;font-size: 50px;">{{ profile.user.username }}</div>
							
							{% if profile.available_for_hire %}
								<div class="clearfix pt-3">
									
									{% if user.id != profile.user.id %}
										<div class="float-left">
											<form action="{% url 'user-action' profile.user.id 'hire' %}" method="POST">
												{% csrf_token %}
												{% if involved %}
													<button class="btn btn-light px-2" disabled> Hire </button>
												{% else %}
													<button class="btn btn-success px-4"> Hire </button>
												{% endif %}
											</form>
										</div>
									{% endif %}
									
									{% if user.is_authenticated %}
										{% if user.id != profile.user.id %}
											<div class="favourite float-right">
												<form methd="POST" action="{% url 'add-favourite' profile.user.id %}">
													{% csrf_token %}
													<button type='submit' class='btn btn-light'>
														{% if is_favourite %}
															<i class="fas fa-heart" style="color: red;"></i>
														{% else %}
															<i class="far fa-heart"></i>
														{% endif %}
													</button>
												</form>
											</div>
										{% endif %}
									{% endif %}
								</div>
							{% endif %}
						</div>
					</div>
					<div class="card user-card">
						<div class="card-body text-center">
							<div class="row mb-3">
								<div class="col-6">
									<b class="text-warning" style="font-size: 45px;">0</b> <br/>
									<b class="text-secondary">Jobs Done</b>
								</div>
								<div class="col-6">
									<b class="text-warning" style="font-size: 45px;">0</b> <br/>
									<b class="text-secondary">Jobs Requested</b>
								</div>
							</div>
							<hr/>
							<span class="sml-text">Member Since {{ profile.user.date_joined.date }}</span>
						</div>
					</div>
				</div>

				{% if profile.available_for_hire %}
					<div class="col-12 col-md-8">
						<div class="card user-card">
							<div class="card-body">
								<div class="row">
									<div class="col-6 py-3">
										<span class="sml-text">Occupation :</span>
										{% if profile.occupation %}
											<b>{{ profile.occupation }}</b>
										{% else %}
											<i class="fas fa-times-circle" style="color:red; width=30px;"></i>
										{% endif %}
									</div>
									<div class="col-6 py-3">
										<!-- <i class="fas fa-envelope" style="width:30px; color:#48b4e0"></i> -->
										<span class="sml-text">Email :</span>
										{% if profile.user.email %}
											<b>{{ profile.user.email }}</b>
										{% else %}
											<i class="fas fa-times-circle" style="color:red; width=30px;"></i>
										{% endif %}
									</div>
									<div class="col-6 py-3">
										<!-- <i class="fas fa-user-graduate" style="width:30px; color: #48b4e0"></i> -->
										<span class="sml-text">Education :</span>
										{% if profile.education %}
											<b>{{ profile.education }}</b>
										{% else %}
											<i class="fas fa-times-circle" style="color:red; width=30px;"></i>
										{% endif %}
									</div>
									<div class="col-6 py-3">
										<!-- <i class="fas fa-globe" style="width:30px; color:#48b4e0"></i> -->
										<span class="sml-text">Webpage :</span>
										{% if profile.website %}
											<a href="{{ profile.website }}"> {{ profile.website }}</a>
										{% else %}
											<i class="fas fa-times-circle" style="color:red; width=30px;"></i>
										{% endif %}
									</div>
									<div class="col-6">
										<span class="sml-text">Price : </span>
										<span style="font-size: 30px;">NRs. <span class="text-success">{{ profile.price }}</span></span>
									</div>
								</div>
								<hr/>
								<span class="sml-text">Tags :</span>
								{% for skill in profile.skills.all %}
									<a href="{% url 'tag-details' skill.slug %}" class="btn btn-info btn-sm" style="border-radius: 2em;min-width: 5em;"> <span class="tag-title">{{ skill }}</span> </a>
								{% endfor %}
								<hr/>
								{% if profile.description %}
									{{profile.description}}
								{% endif %}
							</div>
						</div>

						{% if profile.cover_image %}
						<div class="card user-card">
							<div class="card-body">
								<small>My Work :</small>
								<div id="UserCoverImageIndicators" class="carousel slide mt-3" data-ride="carousel">
									<ol class="carousel-indicators">
										<li data-target="#UserCoverImageIndicators" data-slide-to="0" class="active"></li>
										{% if profile.cover_image2 %}
											<li data-target="#UserCoverImageIndicators" data-slide-to="1"></li>
										{% endif %}
										{% if profile.cover_image3 %}
											<li data-target="#UserCoverImageIndicators" data-slide-to="2"></li>
										{% endif %}
									</ol>
									<div class="carousel-inner">
										<div class="carousel-item active">
											<img class="d-block w-100" src={{ profile.cover_image.url }} alt="First slide">
										</div>
										{% if profile.cover_image2 %}
											<div class="carousel-item">
												<img class="d-block w-100" src="..." alt="Second slide">
											</div>
										{% endif %}
										{% if profile.cover_image3 %}
											<div class="carousel-item">
												<img class="d-block w-100" src="..." alt="Third slide">
											</div>
										{% endif %}
									</div>
									<a class="carousel-control-prev" href="#UserCoverImageIndicators" role="button" data-slide="prev">
										<span class="carousel-control-prev-icon" aria-hidden="true"></span>
										<span class="sr-only">Previous</span>
									</a>
									<a class="carousel-control-next" href="#UserCoverImageIndicators" role="button" data-slide="next">
										<span class="carousel-control-next-icon" aria-hidden="true"></span>
										<span class="sr-only">Next</span>
									</a>
								</div>
							</div>
						</div>
						{% endif %}

						{% if user.is_authenticated %}
							{% if not already_commented %}
								{% if user.id != profile.user.id %}
									<div class="card user-card">
										<div class="card-body">
											<form method="POST" action="{% url 'comment-view' profile.user.id %}">
												{% csrf_token %}
												<div class="form-group">
													<label for="id_body"><b>Write your review here </b></label>
													<textarea name="body" class="form-control" id="id_body"></textarea>
												</div>
												<button type="submit" class="btn btn-success">Post</button>
											</form>
										</div>
									</div>
								{% endif %}
							{% endif %}
						{% else %}
							<div class="card user-card">
								<div class="card-body text-center">
									<a href="{% url 'signup' %}">Sign Up</a> or <a href="{% url 'login' %}">Log In</a> to <b>comment</b> here...
								</div>
							</div>
						{% endif %}

						<div class="accordion" id="accordionExample">
							<div class="card user-card">
								{% if comment_count != 0 %}
									<div class="card-header bg-white" id="headingOne">
										<button class="btn btn-link btn-block text-center collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseOne">
											View All Reviews ({{ comment_count }})
										</button>
									</div>

									<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
										<div class="card-body">
											{% for comment in comments %}
												<div class="media">
													<img src="{% static 'images/default_profile_pic.png' %}" class="mr-3 mt-2 rounded-circle" alt="img" width="40px">
													<div class="media-body">
														<div class="mt-0"><b>{{ comment.user.username}}</b> says,</div>
														{{ comment.body }}
													</div>
												</div>
												<hr/>
											{% endfor %}
										</div>
									</div>

								{% else %}
									<div class="card-body text-center text-secondary">
										No Reviews Yet
									</div>
								{% endif %}
							</div>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

templates/pages/search-results.html
{% extends "base.html" %}

{% block content %}
  <ul>
    {% for result in results %}
      <li>{{ result.user.email }}</li>
    {% endfor %}
  </ul>
{% endblock %}